# ------------ Headers ------------ #
[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "noindex"

# ------------ Redirects ------------ #
# Examples
[[redirects]]
from = "/example"
to = "https://example.com"
force = true

# Social examples
[[redirects]]
from = "/twitter"
to = "https://twitter.com/<user>"
force = true

[[redirects]]
from = "/instagram"
to = "https://instagram.com/<user>"
force = true
