# ------------ Redirects ------------ #

# Donations

[[redirects]]
  from = "/liberapay"
  to = "https://liberapay.com/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/github/sponsor"
  to = "https://github.com/sponsors/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/paypal"
  to = "https://www.paypal.me/Alejandrorr7"
  force = true

[[redirects]]
  from = "/coil"
  to = "https://coil.com/u/AlejandroAkbal"
  force = true