# ------------ Headers ------------ #
[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "noindex"

# ------------ Redirects ------------ #

# Services

[[redirects]]
  from = "/status"
  to = "https://rule-34.instatus.com/"
  force = true

# Social

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/fUhYHSZ"
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/Rule34App"
  force = true

[[redirects]]
  from = "/twitter/bot"
  to = "https://twitter.com/Rule34_Bot"
  force = true

[[redirects]]
  from = "/twitter/furbot"
  to = "https://twitter.com/Rule34_FurBot"
  force = true

# GitHub

[[redirects]]
  from = "/github"
  to = "https://github.com/AlejandroAkbal/Rule-34-App"
  force = true

[[redirects]]
  from = "/github/api"
  to = "https://github.com/AlejandroAkbal/Rule-34-API"
  force = true

[[redirects]]
  from = "/github/android"
  to = "https://github.com/AlejandroAkbal/Rule-34-App-Android"
  force = true

# Donations

[[redirects]]
  from = "/donations"
  to = "https://docs.r34.app/donations"
  force = true

[[redirects]]
  from = "/liberapay"
  to = "https://redirect.akbal.dev/liberapay"
  force = true

[[redirects]]
  from = "/github/sponsor"
  to = "https://redirect.akbal.dev/github/sponsor"
  force = true

[[redirects]]
  from = "/paypal"
  to = "https://redirect.akbal.dev/paypal"
  force = true

[[redirects]]
  from = "/coil"
  to = "https://redirect.akbal.dev/coil"
  force = true
