# ------------ Redirects ------------

# Social

[[redirects]]
  from = "/discord"
  to = "https://discordapp.com/channels/656241666553806861/656481328958799872/672100977893179422"
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/Rule34App"
  force = true

[[redirects]]
  from = "/twitterbot"
  to = "https://twitter.com/Rule34_Bot"
  force = true

[[redirects]]
  from = "/twitterfurbot"
  to = "https://twitter.com/Rule34_FurBot"
  force = true

# GitHub

[[redirects]]
  from = "/github"
  to = "https://github.com/AlejandroAkbal/Rule-34-App"
  force = true

[[redirects]]
  from = "/github/android"
  to = "https://github.com/AlejandroAkbal/Rule-34-App-Android"
  force = true

# Donations

[[redirects]]
  from = "/liberapay"
  to = "https://liberapay.com/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/github/sponsor"
  to = "https://github.com/sponsors/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/paypal"
  to = "https://www.paypal.me/Alejandrorr7"
  force = true

[[redirects]]
  from = "/coil"
  to = "https://coil.com/u/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/brave"
  to = "https://brave.com/rap390"
  force = true
