# ------------ Redirects ------------ #

# Social

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/github"
  to = "https://github.com/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/reddit"
  to = "https://www.reddit.com/user/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/dev.to"
  to = "https://dev.to/alejandroakbal"
  force = true

[[redirects]]
  from = "/medium"
  to = "https://medium.com/@alejandroakbal"
  force = true

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/alejandro-akbal"
  force = true

# Donations

[[redirects]]
  from = "/liberapay"
  to = "https://liberapay.com/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/github/sponsor"
  to = "https://github.com/sponsors/AlejandroAkbal"
  force = true

[[redirects]]
  from = "/paypal"
  to = "https://www.paypal.me/Alejandrorr7"
  force = true

[[redirects]]
  from = "/coil"
  to = "https://coil.com/u/AlejandroAkbal"
  force = true